### ISSUE TITLE
Option to handle warnings as errors

### ISSUE THREAD

**Issue by jkanczler** [Dealogic/webpack-vsts-extension#1]
In the build task settings, there should be a an option to handle Webpack warnings as errors, so instead of partially succeeded, the build has to fail.

**Comment by smattt** [comment]
This would be a nice feature, I'd also appreciate the option to ignore warnings... as I'm not keen on having a partially successful build due to UglifyJS warnings that I don't care much about.

**Comment by jkanczler** [comment]
Thanks for the input, I'll consider it how we can support both options. I suppose pick lists will be the most convenient.

E.g. two new properties: `treat errors as` / `treat warnings as`
And the options of the list: `errors` / `warnings` / `informational messages`.

The `informational messages` means the errors and warnings won't be reported in the issues just in the webpack summary section as informational messages (e.g. ignoring warnings, warnings won't be ended up in a partially succeeded build).

Of course the default for `treat errors as` is `errors` and for `treat warnings as` is `warnings`.

**Comment by jkanczler** [comment]
Already merged to master, waiting for release. The previous comment is still true, just the informational messages name was changed to info. It'll be released next week.
