### ISSUE TITLE
Webpack not available anymore in task

### ISSUE THREAD

**Issue by Zanzas** [Dealogic/webpack-vsts-extension#22]
Hello,

it seems that your webpack task has been updated today. 
It's not anymore possible to use it in project in vsts. 
Do you have more information ?

Thanks.

**Comment by jkanczler** [comment]
What do you mean by that? You can use it as before. It just contains some breaking changes, therefore we've released a version 2.0.x. I just played around with preview flag, now it's removed, it's stable version 2.0.2 now.

**Comment by Zanzas** [comment]
Thanks everything is working correctly with 2.0.2 ! :)

**Comment by jkanczler** [comment]
Just for the record. What was the issue? I would like to understand it, so in the future we can avoid these kind of inconveniences.

**Comment by Zanzas** [comment]
At 11h26 all my build displayed that webpack wasn't available. I checked it was still in my global extensions but impossible to find it when i wanted to use it in a build. I removed and installed 2.0.1 version. I still had the same issue. When u pushed 2.0.2 versions everything worked again.

**Comment by jkanczler** [comment]
Okay, thank you very much for sharing this. Maybe it was because of the preview flags. Unfortunately I haven't been able to find proper documentation about it. I wanted to mark the version 2.0 as preview, then I decided to removing the flag from 2.0.2. Sorry again for the inconveniences.
