### ISSUE TITLE
Support Typescript Config "webpack.config.ts"

### ISSUE THREAD

**Issue by cbfrank** [Dealogic/webpack-vsts-extension#51]
Hello
In Visual Studio 2017, it support to run webpack based on webpack.config.ts, please support this kind of config file.

Thanks

**Comment by jkanczler** [comment]
Are you using the webpack task runner?

**Comment by cbfrank** [comment]
Yes, When developing with Visual Studio 2017, I use the task runner to trigger the webpack build, and also bind it to before build. What should I do to achieve the same process on VSTS?

Thanks

**Comment by jkanczler** [comment]
I've checked it, to make it work in the extension I need to register the ts-node programmatically. The implementation is in progress.

**Comment by cbfrank** [comment]
Thank you very much on help this.

**Comment by jkanczler** [comment]
Sorry for the delay. Be aware you have to install ts-node (including it into package.json). Hopefully it's already there.
