### ISSUE TITLE
Other configure types not available

### ISSUE THREAD

**Issue by mskalniak** [Dealogic/webpack-vsts-extension#57]
When I exported the function instead of object (in my config file) the error appears that wrong schema of config file was used. The documentation says that it is possible to export function instead of object:
https://webpack.js.org/configuration/configuration-types/ 
:)

**Comment by jkanczler** [comment]
Very bad news. The node.js API of the webpack library doesn't supports this. Only the CLI can accept configuration as promise or function. I need more investigation how I can support this.

The whole webpack CLI is a mess imho. For example processing config as a promise is happening in a different location of the source code than processing config as a function.

The config as a function in the other hand makes sense only if you're using webpack CLI. The goal of the function to get the env, and argv object. As I'm wrapping the node.js API, you won't have the chance to provide those to the webpack VSTS task.

I have two options to solve this issue:
* Moving back to use webpack CLI to compile the projects within VSTS.
* Reimplement webpack CLI behavior in a customized way to have a chance to control more things over webpack compilation and still provide features of webpack CLI.

**Comment by mskalniak** [comment]
Thanks for the detailed answer! 
I will use webpack CLI directly, until you make changes or me refactor of the config file.

**Comment by jkanczler** [comment]
From version 4.x it should be supported now as the task is using webpack.js cli again.
