### ISSUE TITLE
styling in the build summary is incorrect

### ISSUE THREAD

**Issue by davesmits** [Dealogic/webpack-vsts-extension#59]
see result; would expect same font and better layout

![stylinh](https://user-images.githubusercontent.com/3148438/31091200-7a1829c2-a7aa-11e7-8368-5aaa5f80ee10.PNG)

**Comment by jkanczler** [comment]
Fixed it in 3.2.2. I'm not sure though that adding a scrollbar is the most appropriate solution. Feedback is welcome.
