### ISSUE TITLE
Support multiple webpack build steps

### ISSUE THREAD

**Issue by jkanczler** [Dealogic/webpack-vsts-extension#6]
Currently only one webpack build step is supported per builds. At least we never tested this scenario.

**Comment by YanlongLi** [comment]
Really need this feature.

**Comment by jkanczler** [comment]
It's in progress. I would like to release it in this week. Basically the plan is that the task's display name will be used to identify the custom section on the build summary page like this:
![How to support multiple build tasks](https://raw.githubusercontent.com/wiki/Dealogic/webpack-vsts-extension/HowToSupportMultipleBuildTasks.png)

Hopefully it'll be okay with you.

**Comment by jkanczler** [comment]
Released in version 0.10.0.
