### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by OneCyrus** [Dealogic/webpack-vsts-extension#61]
is there a way that this task doesn't rely an a specific node version from tfs/vsts.

on the build server we use node 8.x (installed locally and used by npm and yarn). but the webpack task uses a bundled node 6.x version. now we have issues with node-sass because of the different node versions.

```Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x```

is there a way to specify the node.exe location?

**Comment by OneCyrus** [comment]
ok, found a solution with the new "node installer" in tfs 2018.

**Comment by OneCyrus** [comment]
still not working properly. we use node 8.9.1 but this task always switches back to 6.x. the node.exe in the path variable is 8.9.1 but this task uses a 6.x version from somewhere.

**Comment by jkanczler** [comment]
Sorry for the late reply. Are you using a hosted build agent or an on-premise one?

**Comment by jkanczler** [comment]
I could reproduce the issue on Hosted VS2017 agent by Microsoft too. Though I would like to mention that agent is using node.js v6.x by default, so I've used the node installer task to upgrade it to 8.x. It seems node-sass can't be installed properly. It's trying to use node.js 6.x binding. I don't know why. I tried to use the suggested `npm rebuild node-sass --force`, but it didn't help.

**Comment by jkanczler** [comment]
I've noticed an interesting thing, I don't know why it's happening, but I'm going to add here:

From the logs of npm install:
`Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node`

From the logs of webpack task:
```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/index.scss
Module build failed: Error: Missing binding d:\a\1\s\node_modules\node-sass\vendor\win32-x64-48\binding.node
```

So it seems npm install is downloading `win32-x64-57_binding.node`, but sass-loader during webpack is trying to use `win32-x64-48`.

**Comment by jkanczler** [comment]
Ignore my previous comments. The problem exists in the task itself, but still don't know why. The sample project that is using node-sass can successfully built by executing node ./node_modules/webpack/bin/webpack.js or executing node ./index.js where index.js is a custom node.js app that is using the node API of webpack.

**Comment by jkanczler** [comment]
I've found the root cause of the issue. Unfortunately it seems the webpack task itself is running under the node v6.10.3 in case of Hosted VS2017 agent. As the task itself is using the node.js API of webpack in the same process therefore the webpack compilation is happening in node v6.10.3 too.

The solution will be usage of the webpack CLI instead of node.js API as anyway other issues are related to this problem like 

> #50 Add custom arguments to webpack command

> #57 Other configure types not available.

**Comment by OneCyrus** [comment]
thanks for looking into this!

**Comment by jkanczler** [comment]
With version 4.x it should work now. If something is still there, re-open this issue.
