### ISSUE TITLE
Building concurrent multiple Webpack configuration files

### ISSUE THREAD

**Issue by danchristian** [Dealogic/webpack-vsts-extension#70]
I am having trouble building multiple Webpack configuration files. We have a legacy Webpack build and a new Webpack build we are running concurrently. I can build it locally without issue but it fails when building on VSTS. We're using the [npm-run-all](https://www.npmjs.com/package/npm-run-all) module.

This is from my `package.json` file:
```
"watch:vue": "webpack --watch --config ./webpack/webpack.dev.js",
"watch:legacy": "webpack --watch --config ./webpack/legacy.dev.js",
"vue": "webpack --config ./webpack/webpack.prod.js",
"legacy": "webpack --config ./webpack/legacy.prod.js",
"start": "run-p watch:*",
"build": "run-p vue legacy"
```
When using `run-p vue legacy` in the CLI arguments input, the Webpack build passes but doesn't build out any of the files and we'll get an `Could not find file 'dist\account.html'` error in the Build Solution step. 

When using `run-p legacy vue` the Webpack build step fails with `ERROR in multi run-p legacy. Module not found: Error: Can't resolve 'legacy' in 'D:\a\1\s'` etc.

I have tried various other CLI arguments in the extension, but to no avail. Is there anything I am doing wrong? Or should I be running Multiple Build Steps and just use npm-run-all for dev builds?

**Comment by jkanczler** [comment]
I don't understand. If you're using the webpack VSTS task, then it'll do nothing with the package.json file. What's the task definition?

**Comment by danchristian** [comment]
The extension will be looking for `webpack.config.js` in root, correct? But they are in a `/webpack` folder in root, so I would need to say where to look for it in the argument.

I have been using `--config ./webpack/legacy.prod.js` as the CLI argument for a while without error, now I need to build two config files.

Essentially the same as saying:

`"build": "webpack --config ./webpack/webpack.prod.js & webpack --config ./webpack/legacy.prod.js"`

**Comment by jkanczler** [comment]
There's a workingFolder setting for the webpack VSTS task. Then it'll start the webpack-cli from that location. You can set that to `./webpack`. But still, you have to have two distinct webpack VSTS build steps to run the legacy and the new webpack project.

**Comment by danchristian** [comment]
Ok great. I will give that a go! Thanks.

**Comment by danchristian** [comment]
That still won't work for me :(

This is my current structure and the error:

<img width="298" alt="screen shot 2018-04-05 at 13 58 00" src="https://user-images.githubusercontent.com/5786541/38367007-713bd7d4-38d9-11e8-82dd-499716bacc7e.png">
<img width="632" alt="screen shot 2018-04-05 at 13 56 32" src="https://user-images.githubusercontent.com/5786541/38367016-74b32f2a-38d9-11e8-9d26-ad9188da224f.png">
<img width="303" alt="screen shot 2018-04-05 at 13 56 40" src="https://user-images.githubusercontent.com/5786541/38367020-77a7029c-38d9-11e8-9a92-19a995faf075.png">
<img width="326" alt="screen shot 2018-04-05 at 13 56 50" src="https://user-images.githubusercontent.com/5786541/38367034-7ab3fdd2-38d9-11e8-95ae-4a1f5b105fdc.png">
<img width="1394" alt="screen shot 2018-04-05 at 14 02 51" src="https://user-images.githubusercontent.com/5786541/38367256-179a5ccc-38da-11e8-94d9-e57521ed1f8d.png">

**Comment by jkanczler** [comment]
I see. Just the config files are in the `./webpack` folder. Where are the project files? Basically, the working folder should be where you have the `node_modules/webpack/bin/webpack.js`. file. Then you have to specify the location of the configuration files relatively from the working folder.

E.g.:
```
front-end-1/webpack.config.js
front-end-1/node_modules/webpack/bin/webpack.js
front-end-2/webpack.config.js
front-end-2/node_modules/webpack/bin/webpack.js
```
Then the working folder for `front-end-1-webpack` task is `./front-end-1`, but the config is `--config webpack.config.js`.
The working folder For `front-end-2-webpack` task is `./front-end-2`, but the config is `--config webpack.config.js`.

**Comment by danchristian** [comment]
The project files are in root, it's one project file and two different config files. So I guess I need to go back to putting the route in the CLI argument:

`--config /webpack/legacy/webpack.config.js`

**Comment by jkanczler** [comment]
Yes. `./webpack/legacy/webpack.config.js` then.

**Comment by danchristian** [comment]
OK, that is working now. Thank you. Some confusion from my end with Multiple Build Steps.
