### ISSUE TITLE
Add ability to set NODE_ENV

### ISSUE THREAD

**Issue by smattt** [Dealogic/webpack-vsts-extension#8]
We're using your task and it's working well for us so far, thank you for your efforts!

One thing that we'd love to see is the ability to set NODE_ENV=production via a VSTS task option. Has anyone else figured out a nice way to set environment variables in conjunction with this VSTS task?

Thanks

**Comment by jkanczler** [comment]
I suppose you would like to use NODE_ENV variable in the webpack.config.js file something like this:

```
    var filename = 'main.development.js';

    if (process.env.NODE_ENV === 'production') {
        filename = 'main.production.js'
    }
```

If process.env.NODE_ENV is not necessary, then you can use webpack env variable instead:
```
    webpack --env production
```

Then the webpack.config.js export has to be a function, where the argument will be the env:
```
module.exports = function (env) {
    if (env === 'production') {
        ...
    }
}
```

If you still would like to rely on process.env.NODE_ENV, you can define a command line VSTS task before the webpack task.

You have to set the Tool property to echo, the arguments to
```
##vso[task.setvariable variable=NODE_ENV;]production
```

That's the way how you can change an environment variable in your build pipeline for VSTS tasks.

![alt text](https://raw.githubusercontent.com/wiki/Dealogic/webpack-vsts-extension/SettingNodeEnvVariableToProduction.png "SET NODE_ENV=production")

Hopefully that's answer for your question.

**Comment by smattt** [comment]
That's a perfect answer, thanks for helping a WebPack newbie get over these hurdles. I appreciate you taking the time to answer my question so thoroughly!
