### ISSUE TITLE
Warn when watch mode is turned on

### ISSUE THREAD

**Issue by seanjmalone** [Dealogic/webpack-vsts-extension#84]
Like #65 this was my own stupid mistake:
```JS
module.exports = merge(common, {

    watch: true

    // Other stuff...
});
```
Having watch mode left on in your config makes the build output window appear to hang without any errors. Seems obvious why this would be the cause now, but it took several hours to work out.

Perhaps having this issue within reach of an internet search is the only fix needed really.

Otherwise the extension works great for us, thanks!

**Comment by jkanczler** [comment]
Thanks for mentioning this. Closing the issue as I'm going to fix this as a part of #65. See my suggestion there to provide feedback.
