### ISSUE TITLE
Can't add to azure devops build after installed

### ISSUE THREAD

**Issue by ngohungphuc** [Dealogic/webpack-vsts-extension#86]
![chrome_SstnWExXyb](https://user-images.githubusercontent.com/13591213/54924704-8e460c00-4f3f-11e9-897e-88f9417a4715.png)

After installed I dont see add button for this webpack task Any idea ?

**Comment by jkanczler** [comment]
Is it the Microsoft hosted Azure DevOps or on premise TFS? Because I can't see this problem happening in the Microsoft hosted Azure DevOps.

![image](https://user-images.githubusercontent.com/10925650/55951013-8633df00-5c56-11e9-8d5b-44369b4e9020.png)

**Comment by ngohungphuc** [comment]
It's on Azure Devops @jkanczler

**Comment by jkanczler** [comment]
And I assume it's still a problem for you, am I right?

**Comment by ngohungphuc** [comment]
Correct

**Comment by jkanczler** [comment]
Sorry for the late reply. Could you send some details about the build agent? Is that a Microsoft Hosted agent or a custom one?

**Comment by ngohungphuc** [comment]
@jkanczler it's okay now. It's just permission issue.
Sorry for taking your time
