### ISSUE TITLE
Feature request: add ability to pass node options

### ISSUE THREAD

**Issue by metoule** [Dealogic/webpack-vsts-extension#91]
Could you add a way to pass some arguments to the `node` executable, the same way it's possible to add webpack cli arguments? I have a very large webpack project that sometimes fail due to the following error:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

It's a known issue (cf webpack/webpack#6389), and one possible workaround is to use the node options `--max_old_space_size=4096` to increase the heap size. It would be awesome if I could pass those options directly with your extension.

For now, I added an environment variable `NODE_OPTIONS` to my build pipeline, but I'd rather set this for webpack only.

**Comment by jkanczler** [comment]
Added support for it. I'm closing this for now. If something is wrong, please re-open it.

**Comment by metoule** [comment]
It's working perfectly, thank you!
